import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });
import { getServerSession } from "next-auth";
import { authOptions } from "./utils/auth";
import LogoutButton from "@/components/shared/logout-button";
import { getMeUser } from "@/lib/user";
import Providers from "./providers";
import { H1, P } from "@/components/ui/typography";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  const user = await getMeUser();

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <nav className="flex pb-10 justify-between items-center pt-12 max-w-7xl mx-auto px-6">
            <Link
              href="/"
              className="scroll-m-20 text-xl font-extrabold tracking-normal"
            >
              Dads & You
            </Link>

            {session && (
              <div className="flex gap-2 items-center">
                <P className="text-sm">{user && <>{user?.email}</>}</P>
                <LogoutButton />
              </div>
            )}
          </nav>
          <div className="pb-12 space-y-10 max-w-7xl mx-auto px-6">
            {children}
          </div>
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
