import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });
import { getServerSession } from "next-auth";
import { authOptions } from "./utils/auth";
import LogoutButton from "@/components/shared/LogoutButton";
import { getMeUser } from "@/lib/user";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
    const session = await getServerSession(authOptions);
  const user = await getMeUser();

  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="flex justify-between items-center p-4 border-b border-gray-500">
          <div className="flex gap-2">
            <Link href="/">Home</Link>
          <Link href="/auth">Login</Link>
          </div>

          {session && (
            <div className="flex gap-2 items-center">
              {user && <>{user?.email}</>}
              <LogoutButton />
            </div>
          )}
        </nav>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
